import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 5000

[window]
dynamic_padding = false

[window.dimensions]
columns = 120
lines = 30

[terminal]
osc52 = "CopyPaste"
