import = ["~/.config/alacritty/themes/monokai_pro.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "DejaVuSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "DejaVuSansM Nerd Font"
style = "Italic"

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 6

[scrolling]
history = 5000

[window]
dynamic_padding = true

[window.padding]
x = 10

[window.dimensions]
columns = 120
lines = 30

[terminal]
osc52 = "CopyPaste"
