return {
  -- Highlight, edit, and navigate code
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "nvim-treesitter/nvim-treesitter-textobjects",
    "windwp/nvim-ts-autotag",
    "RRethy/nvim-treesitter-endwise",
  },
  opts = {
    indent = { enabled = false },
    autotag = { enable = true },
    endwise = { enable = true },
    ensure_installed = {
      "bash",
      "css",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitcommit",
      "gitignore",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "ruby",
      "sql",
      "tsx",
      "typescript",
      "vim",
      "yaml",
    },
    keymaps = {
      ["im"] = "@block.inner",
      ["am"] = "@block.outer",
    },
  },
}
